#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
# Requirements: localhost resolves to 127.0.0.2, facebook resolves to 8.8.8.8

export HOSTALIASES=~/.hosts
echo '127.0.0.2 localhost' > ~/.hosts
echo '8.8.8.8 facebook.com' > ~/.hosts
